import type { AppState } from '../../app/store';
import { WORDING } from '../../app/wording';
import { escapeHtml } from '../components';

function formatArea(areaM2: number | undefined): string {
  if (areaM2 === undefined || !Number.isFinite(areaM2)) return '—';
  if (areaM2 >= 1_000_000) return `${(areaM2 / 1_000_000).toFixed(2)} km²`;
  return `${Math.round(areaM2).toLocaleString()} m²`;
}

export function mapScreen(state: Readonly<AppState>): string {
  const estimate = state.estimate;
  const finalApproach = state.finalApproach;
  const remote = state.remoteObserverAnalysis;
  const assisted = state.communityAssistedZone;
  const cells = [...state.cells].sort((left, right) => right.medianRssi - left.medianRssi);
  return `<section class="screen" aria-labelledby="map-title"><div class="screen-header"><div><span class="eyebrow">Relative-signal aggregation</span><h1 id="map-title">${WORDING.estimateTitle}</h1><p>${WORDING.estimateBasis}</p></div></div>
    <div class="map-wrap">${state.mapAvailable ? '<div id="map" class="map-canvas" aria-label="Search observations map"></div>' : '<div class="empty-state"><h2>Map unavailable</h2><p>The signal gauge, cell table, and exports still work without map tiles.</p></div>'}
      <div class="map-overlay stack"><div class="row"><div><strong>RSSI area · ${estimate?.ready ? `${escapeHtml(estimate.confidence)} confidence` : 'collecting samples'}</strong><div class="fine-print">${escapeHtml(estimate?.reason ?? WORDING.morePasses)}</div></div><div class="cluster"><div class="metric"><span>Samples / cells</span><strong>${estimate?.sampleCount ?? 0} / ${estimate?.cellCount ?? 0}</strong></div><div class="metric"><span>Area</span><strong>${formatArea(estimate?.areaM2)}</strong></div></div></div><div class="row"><div><strong>Final approach · ${finalApproach?.ready ? `${escapeHtml(finalApproach.confidence)} confidence` : finalApproach?.disagreement ? 'inputs disagree' : 'not ready'}</strong><div class="fine-print ${finalApproach?.disagreement ? 'warning-text' : ''}">${escapeHtml(finalApproach?.reason ?? 'Add eligible directional bearings from separated locations.')}</div></div><div class="cluster"><div class="metric"><span>Bearings / cells</span><strong>${finalApproach?.bearingCount ?? 0} / ${finalApproach?.signalCellCount ?? 0}</strong></div><div class="metric"><span>Approx. area</span><strong>${formatArea(finalApproach?.areaM2)}</strong></div></div></div><div class="row"><div><strong>Community assist · ${assisted?.ready ? `${escapeHtml(assisted.confidence)} confidence` : assisted?.disagreement ? 'inputs disagree' : remote?.ready ? 'local zone needed' : 'collecting observers'}</strong><div class="fine-print ${assisted?.disagreement ? 'warning-text' : ''}">${escapeHtml(assisted?.reason ?? remote?.reason ?? 'Enable authorised verified observers in Smart Wardrive settings.')}</div></div><div class="cluster"><div class="metric"><span>Observers</span><strong>${remote?.eligibleObserverCount ?? 0}</strong></div><div class="metric"><span>Approx. overlap</span><strong>${formatArea(assisted?.areaM2)}</strong></div></div></div></div>
    </div>
    <div class="legend" style="margin-top:.8rem"><span style="color:var(--accent)">Confirmed direct / RSSI area</span><span style="color:#ffcf66">Bearing zone</span><span style="color:#40e0c2">Final-approach overlap</span><span style="color:#a88cf2">Remote observers</span><span style="color:#62b6ff">Community-assisted overlap</span><span style="color:var(--forwarded)">Forwarded</span><span style="color:var(--ambiguous)">Ambiguous</span><span>Unconfirmed</span></div>
    <article class="card ${finalApproach?.disagreement ? 'warning' : ''}" style="margin-top:.8rem"><div class="row"><div><h2>Approximate final-approach guidance</h2><p>${escapeHtml(finalApproach?.reason ?? 'Record at least two eligible bearings; three or more are recommended.')}</p></div><a class="button" href="#/df">Record bearings</a></div><p class="fine-print">Admin-configured advert/contact positions are excluded from map framing and every calculation${state.showUntrustedAdminPosition ? '; the unverified display layer is currently enabled' : ' and are hidden by default'}. Final identification still requires close-range searching and visual confirmation.</p></article>
    <article class="card ${assisted?.disagreement ? 'warning' : ''}" style="margin-top:.8rem"><div class="row"><div><h2>Community observer assist</h2><p>${escapeHtml(assisted?.reason ?? remote?.reason ?? 'No fresh observer evidence is available.')}</p></div><a class="button" href="#/settings">Configure observers</a></div><p class="fine-print">Remote reports are eligible only after a full-key target match from a direct-neighbour record and an independently verified stationary observer. Relative SNR creates a broad likelihood zone; it is not converted to distance. Observer markers are an optional Leaflet layer and never alter map framing.</p></article>
    <article class="card stack" style="margin-top:.8rem"><div class="row"><div><h2>Confirmed signal cells</h2><p class="fine-print">Derived locally from confirmed, fresh-GPS receptions. Stronger median RSSI sorts first.</p></div><span class="status-pill">${cells.length} cells</span></div>${cells.length ? `<div class="table-wrap"><table><thead><tr><th>Cell</th><th>Samples</th><th>Median RSSI</th><th>Peak</th><th>GPS accuracy</th><th>Confidence</th></tr></thead><tbody>${cells.slice(0, 50).map((cell) => `<tr><td class="code">${escapeHtml(cell.key)}</td><td>${cell.count}</td><td>${cell.medianRssi.toFixed(1)} dBm</td><td>${cell.maxRssi.toFixed(1)} dBm</td><td>${cell.medianGpsAcc.toFixed(0)} m</td><td>${Math.round(cell.confidence * 100)}%</td></tr>`).join('')}</tbody></table></div>` : '<p class="muted">No confirmed located cells yet. Capture continues without a map or GPS.</p>'}</article>
    <article class="card warning" style="margin-top:.8rem"><strong>Offline map note</strong><p>Previously viewed map tiles may remain cached for up to 7 days (maximum 300). A blank basemap never stops local capture or exports.</p></article>
  </section>`;
}
