import type { AppState } from '../../app/store';
import { escapeHtml } from '../components';
import { currentTheme, THEMES } from '../theme';

export function settingsScreen(state: Readonly<AppState>): string {
  const settings = state.preferences;
  const selected = (value: string): string => settings.audioMode === value ? 'selected' : '';
  const observerStatuses = new Map(state.observerStatuses.map((status) => [status.observerId, status]));
  const observers = state.observers.length
    ? state.observers.map((observer) => {
        const status = observerStatuses.get(observer.id);
        const detail = observer.accuracyM > 250
          ? 'Audit-only: anchor uncertainty exceeds the 250 m live-analysis limit, so this observer is not polled.'
          : status?.detail
          ?? (status?.lastHeardAt
            ? `Target heard ${new Date(status.lastHeardAt).toLocaleString()} at ${status.lastSnr?.toFixed(1) ?? '?'} dB SNR`
            : 'No target-matched neighbour evidence collected in this browser.');
        return `<article class="card stack"><div class="row"><div><h3>${escapeHtml(observer.label)}</h3><p class="fine-print code">${escapeHtml(observer.repeaterPubkeyHex)}</p></div><span class="status-pill ${observer.enabled ? 'connected' : ''}">${observer.enabled ? escapeHtml(status?.state ?? 'enabled') : 'disabled'}</span></div><p>${observer.lat.toFixed(6)}, ${observer.lon.toFixed(6)} · ±${Math.round(observer.accuracyM)} m · ${escapeHtml(observer.verification.replace('-', ' '))}</p><p class="fine-print">${escapeHtml(detail)}</p><div class="button-group"><button class="button small" data-action="toggle-observer" data-id="${escapeHtml(observer.id)}" data-enabled="${observer.enabled ? 'false' : 'true'}">${observer.enabled ? 'Disable' : 'Enable'}</button><button class="button danger small" data-action="delete-observer" data-id="${escapeHtml(observer.id)}">Remove</button></div></article>`;
      }).join('')
    : '<div class="empty-state"><h3>No verified observers</h3><p>Add only stationary repeaters whose real coordinates and query permission you have independently confirmed.</p></div>';

  return `<section class="screen" aria-labelledby="settings-title"><div class="screen-header"><div><span class="eyebrow">Device preferences</span><h1 id="settings-title">Settings</h1><p>Advanced thresholds affect future aggregation only; raw receptions and observer-query audit events are preserved.</p></div></div>
    <form class="grid two" data-form="settings">
      <article class="card stack"><h2>Appearance and sound</h2><label class="field"><span>Theme</span><select name="theme">${THEMES.map((theme) => `<option value="${theme}" ${theme === currentTheme() ? 'selected' : ''}>${theme}</option>`).join('')}</select></label><label class="field"><span>Audio mode</span><select name="audioMode"><option value="chime" ${selected('chime')}>Chime</option><option value="tone" ${selected('tone')}>Continuous tone</option><option value="geiger" ${selected('geiger')}>Geiger</option><option value="off" ${selected('off')}>Off</option></select></label><label class="field"><span>Master volume (${Math.round(settings.audioVolume * 100)}%)</span><input name="audioVolume" type="range" min="0" max="1" step="0.05" value="${settings.audioVolume}"></label><label class="toggle"><span>Mute audio</span><input name="audioMuted" type="checkbox" ${settings.audioMuted ? 'checked' : ''}></label><label class="toggle"><span>Forwarded-packet alert</span><input name="forwardedAlert" type="checkbox" ${settings.forwardedAlert ? 'checked' : ''}></label></article>
      <article class="card stack"><h2>Aggregation</h2><label class="field"><span>Cell size (metres)</span><input name="cellSizeM" type="number" min="8" max="60" value="${settings.cellSizeM}"></label><p class="fine-print">Mode-safe bounds are 8–20 m for walk and 30–60 m for drive; the app clamps the saved preference and records the effective value in each session.</p><label class="field"><span>Minimum confirmed samples</span><input name="minSamples" type="number" min="3" max="30" value="${settings.minSamples}"></label><label class="field"><span>Minimum occupied cells</span><input name="minCells" type="number" min="2" max="12" value="${settings.minCells}"></label><label class="field"><span>Smoothing window</span><input name="smoothingWindow" type="range" min="3" max="11" step="1" value="${settings.smoothingWindow}"></label><label class="field"><span>EMA response</span><input name="emaAlpha" type="range" min="0.2" max="0.6" step="0.05" value="${settings.emaAlpha}"></label><label class="field"><span>GPS hard accuracy limit (metres)</span><input name="maxGpsAccuracyM" type="number" min="25" max="200" value="${settings.maxGpsAccuracyM}"></label></article>
      <article class="card stack"><h2>Smart Wardrive</h2><label class="toggle"><span>Enable foreground automation</span><input name="smartWardriveEnabled" type="checkbox" ${settings.smartWardriveEnabled ? 'checked' : ''}></label><label class="toggle"><span>Send automatic repeater discovery pulses</span><input name="autoDiscoveryEnabled" type="checkbox" ${settings.autoDiscoveryEnabled ? 'checked' : ''}></label><label class="field"><span>Discovery interval (seconds)</span><input name="autoDiscoveryIntervalSec" type="number" min="60" max="900" value="${settings.autoDiscoveryIntervalSec}"></label><label class="toggle"><span>Query authorised community observers</span><input name="observerAssistEnabled" type="checkbox" ${settings.observerAssistEnabled ? 'checked' : ''}></label><label class="field"><span>Observer poll interval (minutes)</span><input name="observerPollIntervalMin" type="number" min="5" max="60" value="${settings.observerPollIntervalMin}"></label><p class="warning-text">Automation runs only during a real Drive session while this page is visible and the companion protocol is fully connected. Discovery and observer queries transmit over shared LoRa airtime; use conservative intervals and comply with your local radio rules.</p></article>
      <article class="card stack"><h2>Untrusted map reference</h2><label class="toggle"><span>Show admin-configured target position</span><input name="showUntrustedAdminPosition" type="checkbox" ${state.showUntrustedAdminPosition ? 'checked' : ''}></label><p class="warning-text">Advert and contact coordinates are manually configured by a repeater admin and may be wrong. This layer is labelled unverified and is never used for map framing, signal cells, search areas, observer anchors, or final-approach calculations.</p><p class="fine-print">This preference is stored only in this browser for this site origin.</p></article>
      <button class="button primary" type="submit">Save settings</button>
    </form>
    <section class="stack" style="margin-top:1rem" aria-labelledby="observer-title"><div class="screen-header"><div><span class="eyebrow">Opt-in remote evidence</span><h2 id="observer-title">Verified community observers</h2><p>Blank guest access is attempted once per enabled observer connection. Failed logins stop; passwords are never guessed or stored.</p></div><button class="button" data-action="poll-observers" ${state.activeSession?.mode === 'drive' && !state.activeSession.demo && state.connection === 'connected' ? '' : 'disabled'}>Poll enabled observers now</button></div>
      <form class="card grid two" data-form="observer"><label class="field"><span>Observer label</span><input name="label" required maxlength="80" placeholder="North ridge repeater"></label><label class="field"><span>Full 32-byte public key</span><input name="pubkey" required minlength="64" maxlength="96" autocomplete="off" class="code"></label><label class="field"><span>Verified latitude</span><input name="lat" type="number" step="any" min="-90" max="90" required></label><label class="field"><span>Verified longitude</span><input name="lon" type="number" step="any" min="-180" max="180" required></label><label class="field"><span>Coordinate accuracy (metres)</span><input name="accuracyM" type="number" min="1" max="250" value="20" required></label><label class="field"><span>Verification method</span><select name="verification"><option value="operator-confirmed">Confirmed by operator</option><option value="user-surveyed">Surveyed by me</option></select></label><label class="toggle"><span>I have permission to query this repeater</span><input name="permissionConfirmed" type="checkbox" required></label><div><button class="button primary" type="submit">Save verified observer</button></div><p class="warning-text" style="grid-column:1/-1">Do not copy coordinates from an advert/contact into these fields. Those remain untrusted admin metadata. Anchors worse than 250 m are not eligible for live polling or location analysis.</p></form>
      <div class="grid two">${observers}</div>
    </section>
  </section>`;
}
