import type { AppState } from '../../app/store';
import { currentTheme, THEMES } from '../theme';

export function settingsScreen(state: Readonly<AppState>): string {
  const settings = state.preferences;
  const selected = (value: string): string => settings.audioMode === value ? 'selected' : '';
  return `<section class="screen" aria-labelledby="settings-title"><div class="screen-header"><div><span class="eyebrow">Device preferences</span><h1 id="settings-title">Settings</h1><p>Advanced thresholds affect future classification-independent signal aggregation only; raw receptions are always preserved.</p></div></div>
    <form class="grid two" data-form="settings">
      <article class="card stack"><h2>Appearance and sound</h2><label class="field"><span>Theme</span><select name="theme">${THEMES.map((theme) => `<option value="${theme}" ${theme === currentTheme() ? 'selected' : ''}>${theme}</option>`).join('')}</select></label><label class="field"><span>Audio mode</span><select name="audioMode"><option value="chime" ${selected('chime')}>Chime</option><option value="tone" ${selected('tone')}>Continuous tone</option><option value="geiger" ${selected('geiger')}>Geiger</option><option value="off" ${selected('off')}>Off</option></select></label><label class="field"><span>Master volume (${Math.round(settings.audioVolume * 100)}%)</span><input name="audioVolume" type="range" min="0" max="1" step="0.05" value="${settings.audioVolume}"></label><label class="toggle"><span>Mute audio</span><input name="audioMuted" type="checkbox" ${settings.audioMuted ? 'checked' : ''}></label><label class="toggle"><span>Forwarded-packet alert</span><input name="forwardedAlert" type="checkbox" ${settings.forwardedAlert ? 'checked' : ''}></label></article>
      <article class="card stack"><h2>Aggregation</h2><label class="field"><span>Cell size (metres)</span><input name="cellSizeM" type="number" min="8" max="60" value="${settings.cellSizeM}"></label><p class="fine-print">Mode-safe bounds are 8–20 m for walk and 30–60 m for drive; the app clamps the saved preference and records the effective value in each session.</p><label class="field"><span>Minimum confirmed samples</span><input name="minSamples" type="number" min="3" max="30" value="${settings.minSamples}"></label><label class="field"><span>Minimum occupied cells</span><input name="minCells" type="number" min="2" max="12" value="${settings.minCells}"></label><label class="field"><span>Smoothing window</span><input name="smoothingWindow" type="range" min="3" max="11" step="1" value="${settings.smoothingWindow}"></label><label class="field"><span>EMA response</span><input name="emaAlpha" type="range" min="0.2" max="0.6" step="0.05" value="${settings.emaAlpha}"></label><label class="field"><span>GPS hard accuracy limit (metres)</span><input name="maxGpsAccuracyM" type="number" min="25" max="200" value="${settings.maxGpsAccuracyM}"></label></article>
      <button class="button primary" type="submit">Save settings</button>
    </form>
  </section>`;
}
